sync_address = ""
auto_sync = false
style = "compact"
inline_height = 10
show_preview = true
search_mode = "fuzzy"
filter_mode_shell_up_key_binding = "directory"
update_check = false
enter_accept = true
dialect = "uk"
workspaces = true
show_help = false
show_tabs = false
exit_mode = "return-query"

[sync]
records = true
